language: scala

scala:
  - 2.12.2

jdk:
  - openjdk8

script:
  - sbt +clean coverage +claperJVM/test coverageReport coverageAggregate coverageOff +test

after_success:
  - sbt coveralls

before_deploy:
  - openssl aes-256-cbc -pass pass:$PGP_PASSPHRASE -in secret.asc.enc -out local.secret.asc -d
  - echo $PGP_PASSPHRASE | gpg --batch --passphrase-fd 0 --import local.secret.asc

deploy:
  skip_cleanup: true
  provider: script
  script: sbt +publishSigned sonatypeBundleRelease
  on:
    tags: true

after_deploy:
  - gpg --batch --delete-secret-keys B89EBE31B8541C9AB694A7063926C2AF62D1F8D5

env:
  global:
    - secure: "gSADu/D+fuUIG6rIwn4r/BdI6UYKyfISjfc4J71K3UH0jwsYnKbI/xeuEsi5tYnHSf2cb+0mrsovqMguK8ARAlTyDIGkcBnSs6bXk+3pfH0OjP/Kh8U31hjQMT5WkqGfZBkrOloc7gJSzhMwmVkaOPb2lKZ0ku0Uw/hFpMKq6nXD17iwCvd5BV1SaT/lUaGq7cgxDRpYB2tVvVrS5kk9dU7+D7ASo8Wx/SyYl8PEcK5d4JjwcF815GuHBeSPBjzTrQsowqvN2nN4IWaojRqVAC6cnZv4atPFabFQWFvAZ7sgYhHrUARRTs7bWaTARxNhHmfx/fbHh2Oz6kE6y5NMz/YJa1W6edPTeGqDkT2XS7wDDGhVVrt5IPAjs/F3pGVr4jYd5xTDg+6C2SSC0rrdfW8XoZ7mAastv1lZQaW8iu1P3aqMes97g/QOwN5KVTbuWhA/VhHJALCPjFUB+v8l84EzT36gHAyJO1eHXhwbltyeuvyaiwJB8/sC9YbZWCZd6ACeh6qO9CEdzQygNcBFkCXJTBWch/ZqmcAHxmVk2Wooe3cUxVJWKC7cdnAZ3+nkJFthbjIcGmXhV8x3o0M/z09MysbcduTXxpmiU2vvpEP4GqxTMQIkDzpJivO4kDltSR6bOdfIgJAg6JyJ0tALCc9hvZBcHKSE9liT+aZF/WM="
    - secure: "TR8jSl6tv2LhV9wwB7JAj7ubbMKv1dxtY/R95Bjs4o3NfX735pX4hienbU21NUcxMwNdGgb36ZtfKQbdNE4s0olV2ZvWN8ZtoiJ1mhhIAL2FKn+crR8lLILfmDN17u5G4NrXE0z2mc25Zw2hW1Xv6q6A8MqL+NM2MCOA/45kXnxYpRzhVM4/VKqLYoCCRNrEAPeTNJzIFcd1w3/TvKDw2UQ+bJV22H90wQbli1N9j5t5k4eUQmmOlYXw2d8YPum1yHr6+BgB63MRwU13DHAbLvtxQ3HOzhCBKNP+NV6V9aHMmvc5iNkpnTtf9zxQAF7QocYZMbdex2k7ZW0X5QhoJeqmRILP9UcL4GF1lRQUTqFxuREH2f+dQ7EUkg7E0SNLcOlkLgy21gvqu7L9xpGmDGwhmRWqpEKbTGeJxBm9lTx7B+zDV1K50FA2lEomO5ozZWlg0yzd038QTv34q3xIvHx+wvLQu9oXbTWcdrp9WJyy0wAjJDNxDXTl5xoEb4pTlUAC3q0FCMl+ifpnAgf2nIVb/hIxFiRgyp46LrVTs9rVmOg8YqHhA6ZhKjS83xlmbK/UUTz0FHAboPW9+YTlaJnhaLy6n1YUgGTByi33Jqev1jCy8seLqkjFwvzzdQCRNKWmt+5wzgoT8oNXwW+FCNhgaBzoAjqJ7LfF+/xZhI8="
    - secure: "yKmnFu4D1adONxUZDSxT4+C4YVNnkjwoDx0KPYGh6NllzB4nwLGF80IyloSCEw1xx8UlM1KBaTDoHrVsCm1DRKxJCJOeCRDyqWPzlytweNmyIymV8+gaAtKJxb/B/N0wkyfbAB4ZOcWY5lyAyqtDwMPvvw9yuzTIAr+hAH9o5Fq23caSCMabsiXFgANZq91fejnQe70muMq++6MmkosGooV4H84nVdGD+DU4fsAm8t1KiDjaEg1V3PuTzvdgfKDGBwdCugvWm5KFR5Vuh0WhmIrVBpP7dj7Vg7+td2I2cie7FyXJhne5f5Fb4XjlIYyiUSRuwN6phiS+p1fbRbwF/04BK9KVM+AuH3QNzE2zHX8qEPLxg7B7KPKVoygX4bPyoo51T1w3P/fm1V4yIt4GZP2lTcIp0bYOrSGwk20+enlHncXMaN4VjK0DsNmp+WNI8JXu2QznQ2T7XhJqYP9wmkuysp0CXNfm3JDfTWeWWhmFUCwREAbyJbHliqJmIRruO0ZnIWfG4GmlO6LPNDiu7pTd847+BJASWVai9/URDoKwjfSOt1loAdO2RiJUp5plHkuJzFdyQS7m4SmNpTtkiFaR4Wa6BrvD0pE9DnLpgQkcJERRddqBQeCxA7n3o/VuU28a8VQ3pwtWo9cHcwKT0/F2nh/nYTKojOx4x/GvlWI="
